apiVersion: v1
kind: ConfigMap
metadata:
  name: auction-svc-config
data:
  ASPNETCORE_ENVIRONMENT: Docker
  ASPNETCORE_URLS: http://+:80;http://+:7777
  RabbitMq__Host: rabbitmq-clusterip.default.svc.cluster.local
  IdentityServiceUrl: http://identity-clusterip
  Kestrel__Endpoints__Grpc__Protocols: Http2
  Kestrel__Endpoints__Grpc__Url: http://+:7777
  Kestrel__Endpoints__WebApi__Protocols: Http1
  Kestrel__Endpoints__WebApi__Url: http://+:80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: search-svc-config
data:
  ASPNETCORE_ENVIRONMENT: Docker
  ASPNETCORE_URLS: http://+:80
  RabbitMq__Host: rabbitmq-clusterip.default.svc.cluster.local
  AuctionServiceUrl: http://auction-clusterip

  
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: bid-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMq__Host: rabbitmq-clusterip.default.svc.cluster.local
  IdentityServiceUrl: http://identity-clusterip
  GrpcAuction: http://auction-clusterip:7777

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: notify-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMq__Host: rabbitmq-clusterip.default.svc.cluster.local
  RabbitMq__Username: rabbit
  RabbitMq__Password: rabbitpw
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  ClientApp: https://app.carbidder.local
  IdentityServiceUrl: http://identity-clusterip

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  IssuerUri: https://id.carbidder.local
  ClientApp: https://app.carbidder.local

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-svc-config
data:
  API_URL: http://gateway-clusterip/
  ID_URL: https://id.carbidder.local
  ID_URL_INTERNAL: http://identity-clusterip
  AUTH_URL: https://app.carbidder.local
  AUTH_URL_INTERNAL: http://webapp-clusterip:3000
  NOTIFY_URL: https://api.carbidder.local/notifications