apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: carbidder-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - app.carbidder.local
    - api.carbidder.local
    - id.carbidder.local
    secretName: carbidder-app-tls
  rules:
  - host: app.carbidder.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp-clusterip
            port:
              number: 3000
  - host: api.carbidder.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gateway-clusterip
            port:
              number: 80
  - host: id.carbidder.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: identity-clusterip
            port:
              number: 80
